<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9d2db158-961f-43eb-aeab-ea00e4eadc2f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.56.0" />
    <PackageReference Include="NewHorizonLib" Version="1.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
  </ItemGroup>

</Project>
